version: '3.1'

services:
  dbsimulacro:
    image: postgres:latest
    ports:
      - "5484:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ms-simulacro
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    
    