version: "1"

services:
   broker:
    image: johnnypark/kafka-zookeeper:2.6.0
    container_name: service-broker
    restart: "no"
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
    - ADVERTISED_HOST=127.0.0.1
    - NUM_PARTITIONS=3
    networks:
    - td2025
   redis:
    image: redis:alpine
    container_name: redis-server
    ports:
      - "6379:6379"
    networks:
    - td2025
    
networks:
  td2025:
    name: ms-unu-kafka