version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: msexamen-postgres
    environment:
      - POSTGRES_DB=examendb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123
    ports:
      - "5455:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
