version: "3.9"

services:

  postgres-gestion-legal:
    image: postgres:17
    container_name: postgres-gestion-legal
    restart: always
    environment:
      POSTGRES_DB: db_gestion_legal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5444:5432"
    volumes:
      - pgdata_gestion_legal:/var/lib/postgresql/data

  ms-gestion-legal:
    build: .
    container_name: ms-gestion-legal
    restart: always
    depends_on:
      - postgres-gestion-legal
    ports:
      - "8092:8092"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-gestion-legal:5432/db_gestion_legal
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

volumes:
  pgdata_gestion_legal:
