services:
  postgres-gestion-legal:
    image: postgres:17
    container_name: postgres-gestion-legal
    restart: always
    environment:
      POSTGRES_DB: db_gestion_legal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5444:5432"
    volumes:
      - pgdata_gestion_legal:/var/lib/postgresql/data

volumes:
  pgdata_gestion_legal:
