version: '3.8'
services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-posgrado
    restart: always
    ports:
      - "3310:3306"     # Localhost:3310 â†’ Contenedor:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_ms_posgrado
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
