version: "1"

services:
  mysql:
    image: mysql:latest
    container_name: db-mysql
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=Unu#2025
    ports:
    - 3307:3306
    - 33061:33060
    networks:
    - td2025 
    
networks:
  td2025:
    name: ms-unu

