version: "3.8"

services:
  mysql:
    image: mysql:8.0.26
    container_name: database-mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=Unu#2025
      - MYSQL_DATABASE=unu_caja
    ports:
      - "3307:3306"
      - "33061:33060"
    networks:
      - td2025
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  redis:
    image: redis:7.0-alpine
    container_name: cache-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - td2025

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - td2025

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: broker-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - td2025

networks:
  td2025:
    name: ms-unu-network
